
# Supported prompt refinement techniques: Basic, RecursiveEval, MedPrompt
# Uncomment techniques that you want to use
############################ Critique Task Description Start ############################
prompt_technique_name: "critique_n_refine"
# unique_model_id of model defined in llm_config.yaml
unique_model_id: gpt-4o-mini
# Number of iterations for conducting <mutation_rounds>  rounds of mutation of task description
# followed by refinement of instructions
mutate_refine_iterations: 3
# Number of rounds of mutation to be performed when generating different styles
mutation_rounds: 3
# Refine instruction post mutation
refine_instruction: true
# Number of iterations for refining task description and in context examples for few-shot
refine_task_eg_iterations: 3
# Number of variations of prompts to generate in given iteration
style_variation: 5
# Number of questions to be asked to LLM in a single batch, during training step
questions_batch_size: 1
# Number of batches of questions to correctly answered, for a prompt to be considered as performing good
min_correct_count: 3
# Max number of mini-batches on which we should evaluate our prompt
max_eval_batches: 6
# Number of top best performing prompts to be considered for next iterations
top_n: 1
# Description of task. This will be fed to prompt
#task_description: "You are a underwriter for corporate, commercial and securitization loans. Generate graph reasoning for given attribute to extract the value. You are given attribute Interest Rate Spread for which to extract from credit agreement you need to extract value based on For floating rate credit facilities, list spread over base rate in basis points. If the credit facility is fixed  populate ‘NA’. If the facility includes multiple draws with different spreads, provide the spread that approximates the overall spread on the facility."
task_description: "You are an Expert Commercial Credit Officer. Plan, strategize, and think step by step. Interest rate floor may be derived from Benchmark Rates that may be Minimum Interest Rate, Base Rate, Term SOFR, Advance Rate, Applicable Rate etc. Interest Rate Floor means the value or percentage that the Benchmark Rate or specific rate cannot fall below which is usually zero. Determine the percentage value of the floor and return that value. \n3. Do not return this example as an answer. If the value is not mentioned in the provided text, return None. If the value of the floor is expressed as bps, divide it by 10000 but if it is in percentage divide by 100 otherwise retain its value. For example if Term SOFR shall be less than zero, such rate shall be deemed 0.25% will return 0.0025. Provide the rationale for your answer. Recheck your answer."
# Base instruction, in line with your dataset. This will be fed to prompt
base_instruction: "Lets think step by step and generate graphical reasoning to come to response."
# Instruction for specifying answer format
answer_format: "For each question present the reasoning followed by the correct answer."
# Number of samples from dataset, set aside as training data. In every iteration we would be drawing
# `questions_batch_size` examples from training data with replacement.
seen_set_size: 0
# Number of examples to be given for few shots
few_shot_count: 0
# Number of synthetic training examples to be generated
num_train_examples: 0
# Generate synthetic reasoning
generate_reasoning: true
# Generate description of an expert which can solve the task at hand
generate_expert_identity: true
# Generate keywords that describe the intent of the task
generate_intent_keywords: true
############################ Critique Task Description End ############################



